sudo: false
language: ruby
cache: bundler
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - "2.1"
  - "2.2"
  - "ruby-head"
  - "rbx"
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: ruby-head
    - rvm: rbx
addons:
  apt:
    packages:
    - xpra
    - xserver-xorg-video-dummy
    - g++
    - libxrandr-dev
    - libfox-1.6-dev
    - libfxscintilla-dev
    - swig
before_install:
  - ls -l /usr/lib/libfxscintilla*
  - ln -s /usr/lib/libfxscintilla.so.19 tmp/`ruby -e 'print RUBY_PLATFORM'`/fox16_c/`ruby -e 'print RUBY_VERSION'`/libfxscintilla.so
  - bundle install
before_script:
  - "xpra --xvfb=\"Xorg +extension GLX -config `pwd`/test/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log\"  start :9"
script: bundle exec rake test DISPLAY=:9
after_script:
  - "xpra stop :9"
  - "cat ~/.xpra/*"
