init:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET RAKEOPT=-rdevkit
install:
  - ruby --version
  - gem --version
  - c:/msys64/usr/bin/bash -lc "pacman -S --noconfirm --needed ${MINGW_PACKAGE_PREFIX}-fox ${MINGW_PACKAGE_PREFIX}-swig"
  - swig -version
  - bundle install
build_script:
  - bundle exec rake compile
test_script:
  - bundle exec rake test
environment:
  matrix:
    - ruby_version: "24"
      MINGW_PACKAGE_PREFIX: "mingw-w64-i686"
    - ruby_version: "24-x64"
      MINGW_PACKAGE_PREFIX: "mingw-w64-x86_64"
